### ISSUE TITLE
Breaking update

### ISSUE THREAD

**Issue by ecarter202** [plandem/ooxml#2]
Looks like when you removed:``` type StreamReaderIterator func(cb StreamReaderCallback) bool``` from ```stream_reader.go``` it broke xlsx2go

Now I'm getting: ```../../github.com/plandem/xlsx/sheet_readstream.go:19:13: undefined: ooxml.StreamReaderIterator``` when running my code.

Thanks.

**Comment by plandem** [comment]
Hi. Do you use go modules? Streaming was refactored in 1.0.5

**Comment by plandem** [comment]
xlsx2go should use version from 07/10/2019 with go modules

**Comment by ecarter202** [comment]
I do not use go modules. But I have attempted to for use of this package, and after initializing the go.mod, then running go run *.go I'm receiving the following error:

```go: github.com/plandem/xlsx2go@v0.0.0-20190710031636-e5ade9fd783a: parsing go.mod: unexpected module path "github.com/plandem/xlsx"```

**Comment by ecarter202** [comment]
nvm got it. pain in the ass. hopefully the modules make more sense eventually.

**Comment by plandem** [comment]
They going to make it permanent in August, I hope it will be better, because right now it's pain in ass to work with own dependence :)

**Comment by plandem** [comment]
I tagged v1.0.0 of xlsx2go with a guide that covers most features

**Comment by ecarter202** [comment]
i think i'll just undo all of the changes you made using modules in my forked version. modules seems like too big of a hassle.

**Comment by plandem** [comment]
No need right now, master of xlsx2go was updated. So right now everything should work even without modules.

**Comment by ecarter202** [comment]
okay ya. i just removed the go mod file from the repo and it works. geezus. scared me for a minute.

thanks for the quick responses.

**Comment by plandem** [comment]
before: 
master xlsx2go used ooxml v1.0.4

now:
master xlsx2go uses ooxml v1.1.0

**Comment by plandem** [comment]
https://plandem.github.io/xlsx2go/

thats a guide i was talking about
